package com.jiuting.mapper;

import com.jiuting.pojo.TChatMsg;
import java.util.List;

public interface TChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int insert(TChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    TChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    List<TChatMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int updateByPrimaryKey(TChatMsg record);
}