package com.jiuting.mapper;

import com.jiuting.pojo.TFrientRequest;
import java.util.List;

public interface TFrientRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int insert(TFrientRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    TFrientRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    List<TFrientRequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    int updateByPrimaryKey(TFrientRequest record);
}