package com.jiuting.pojo;

import java.util.Date;

public class TChatMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.send_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.receive_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String receiveUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.sign_flag
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private Integer signFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_msg.creat_time
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private Date creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.id
     *
     * @return the value of t_chat_msg.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.id
     *
     * @param id the value for t_chat_msg.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.send_user_id
     *
     * @return the value of t_chat_msg.send_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.send_user_id
     *
     * @param sendUserId the value for t_chat_msg.send_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setSendUserId(String sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.receive_user_id
     *
     * @return the value of t_chat_msg.receive_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.receive_user_id
     *
     * @param receiveUserId the value for t_chat_msg.receive_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setReceiveUserId(String receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.msg
     *
     * @return the value of t_chat_msg.msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.msg
     *
     * @param msg the value for t_chat_msg.msg
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.sign_flag
     *
     * @return the value of t_chat_msg.sign_flag
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public Integer getSignFlag() {
        return signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.sign_flag
     *
     * @param signFlag the value for t_chat_msg.sign_flag
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setSignFlag(Integer signFlag) {
        this.signFlag = signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_msg.creat_time
     *
     * @return the value of t_chat_msg.creat_time
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_msg.creat_time
     *
     * @param creatTime the value for t_chat_msg.creat_time
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
}