package com.jiuting.pojo;

public class TMyFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_friend.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_friend.my_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String myUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_friend.my_friend_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String myFriendUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_friend.id
     *
     * @return the value of t_my_friend.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_friend.id
     *
     * @param id the value for t_my_friend.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_friend.my_user_id
     *
     * @return the value of t_my_friend.my_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_friend.my_user_id
     *
     * @param myUserId the value for t_my_friend.my_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setMyUserId(String myUserId) {
        this.myUserId = myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_friend.my_friend_user_id
     *
     * @return the value of t_my_friend.my_friend_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getMyFriendUserId() {
        return myFriendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_friend.my_friend_user_id
     *
     * @param myFriendUserId the value for t_my_friend.my_friend_user_id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setMyFriendUserId(String myFriendUserId) {
        this.myFriendUserId = myFriendUserId;
    }
}