package com.jiuting.pojo;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.face-img
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String faceImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.face-img-big
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String faceImgBig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nick-name
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.qrcode
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.cid
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.face-img
     *
     * @return the value of t_user.face-img
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getFaceImg() {
        return faceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.face-img
     *
     * @param faceImg the value for t_user.face-img
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setFaceImg(String faceImg) {
        this.faceImg = faceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.face-img-big
     *
     * @return the value of t_user.face-img-big
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getFaceImgBig() {
        return faceImgBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.face-img-big
     *
     * @param faceImgBig the value for t_user.face-img-big
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setFaceImgBig(String faceImgBig) {
        this.faceImgBig = faceImgBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nick-name
     *
     * @return the value of t_user.nick-name
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nick-name
     *
     * @param nickName the value for t_user.nick-name
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.qrcode
     *
     * @return the value of t_user.qrcode
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.qrcode
     *
     * @param qrcode the value for t_user.qrcode
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.cid
     *
     * @return the value of t_user.cid
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.cid
     *
     * @param cid the value for t_user.cid
     *
     * @mbggenerated Sat Jul 25 20:16:10 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid;
    }
}